config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'subjects#index'

  resources :subjects do
    resources :messages do
      member do
        get 'reply', to: 'messages#reply'  # Ajoutez cette ligne ici
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  belongs_to :quoted_message, class_name: "Message", optional: true, foreign_key: "quote_id"
  has_many :replies, class_name: "Message", foreign_key: "parent_id", dependent: :destroy

  def full_quote
    
    current_message = self
    quotes = []
    while current_message.quoted_message
      quotes << current_message.quoted_message
      current_message = current_message.quoted_message
    end
    quotes.reverse
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subjects
  has_many :messages
  validates :name, presence: true, length: { maximum: 50 }
  # Define permission to edit a message
  def can_edit?(message)
    self.id == message.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
  end
  

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_subject
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!  # Assurez-vous d'utiliser une méthode d'authentification adaptée
  before_action :check_edit_permission, only: [:edit, :update]


  # GET /messages
  def index
    @messages = @subject.messages.all
  end

  # GET /messages/1
  def show
    @message = Message.find(params[:id])
  end

  # GET /messages/new
  def new
    @subject = Subject.find(params[:subject_id])
    @message = @subject.messages.new(parent_id: params[:parent_id])
  end
  
  
  # GET /messages/1/edit
  def edit
    if @message.created_at < 5.minutes.ago
      redirect_to subject_message_path(@subject, @message), alert: "You can only edit this message within 5 minutes of its creation."
    end
  end

  def update
    @message = Message.find(params[:id])
    if @message.update(message_params)
      redirect_to subject_path(@subject), notice: 'Message was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  
  # POST /messages
  def create
    @subject = Subject.find_by(id: params[:subject_id])
    return redirect_to subjects_path, alert: "Subject not found." if @subject.nil?
  
    @message = @subject.messages.build(message_params)
    @message.user = current_user # Ensure this assignment is correct, given your user session management
  
    if @message.save
      redirect_to subject_path(@subject), notice: 'Message created successfully.'
    else
      render :new
    end
  end

  # DELETE /messages/1
  def destroy
    @message.destroy
    redirect_to subject_path(@subject), notice: 'Message was successfully destroyed.'
  end

  def reply
    @subject = Subject.find(params[:subject_id])  # Assurez-vous d'avoir cette ligne
    @message = @subject.messages.find(params[:id])
    render partial: 'messages/quote_preview', locals: { message: @message }
  end
  

  private
    # Use callbacks to share common setup or constraints between actions
    def set_subject
      @subject = Subject.find_by(id: params[:subject_id])
      if @subject.nil?
        flash[:error] = "Subject not found."
        redirect_to subjects_path and return
      end
    end
    
    def set_message
      @message = @subject.messages.find_by(id: params[:id])
      unless @message
        redirect_to subject_messages_path(@subject), alert: "Message not found."
      end
    end
    

    # Only allow a list of trusted parameters through
    def message_params
      params.require(:message).permit(:content, :user_id, :subject_id, :quote_id, :parent_id)
    end    

    def check_edit_permission
      message = Message.find(params[:id])
      unless current_user.can_edit?(message)
        redirect_to(subject_path(message.subject), alert: "You are not allowed to edit this message.")
      end
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]

  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1 or /subjects/1.json
  def show
    @subject = Subject.find(params[:id])
    @messages = @subject.messages
  end


  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects or /subjects.json
  def create
    @subject = current_user.subjects.build(subject_params)

    if @subject.save
      redirect_to @subject, notice: "Subject was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy!

    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "Subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
      unless @subject
        redirect_to root_path, alert: 'Subject not found.'
      end
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def youtube_embed(content)
      youtube_url_regex = /(?:https?:\/\/)?(?:www\.)?(youtube\.com\/watch\?v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/
      content.gsub(youtube_url_regex) do |url|
        video_id = URI.parse(url).query.split('v=').last.split('&').first rescue url.split('/').last
        <<-HTML.squish.html_safe
          <iframe width="560" height="315" src="https://www.youtube.com/embed/#{video_id}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        HTML
      end.html_safe
    end
  end
  

app/helpers/messages_helper.rb
module MessagesHelper
    def can_edit_message?(message)
      message.created_at >= 5.minutes.ago
    end
end
  

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agora</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'logo.png'%>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <meta name="csrf-token" content="<%= form_authenticity_token %>">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container">
    <!-- Logo de l'application -->
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt: "Logo de votre application", style: "width: 40px; height: 40px;" %>
    <% end %>
    
    <!-- Barre de recherche au centre -->
    <form class="form-inline mx-auto">
      <input class="form-control mr-sm-2" type="search" placeholder="Recherche" aria-label="Search">
    </form>

    <!-- Image de l'utilisateur à droite -->
    <div class="navbar-text ml-auto">
      <img src="/assets/user.png" alt="Image de l'utilisateur" class="rounded-circle">
    </div>
  </div>
</nav>


<nav class="navbar-left">
  <%= link_to "Home", root_path %>
  <a href="/explore">Explore</a>
  <a href="/notifications">Notifications</a>
  <a href="/messages">Direct Messages</a>
  <a href="/DMoilheure/lists">Lists</a>
  <a href="/i/bookmarks">Bookmarks</a>
  <a href="/DMoilheure/communities">Communities</a>
  <a href="/i/premium_sign_up">Premium</a>
  <a href="/DMoilheure" class="profile">Profile</a>
  <% if user_signed_in? %>
      <!-- Replace form with a link for logout -->
      <%= button_to "Se déconnecter", destroy_user_session_path, method: :delete, form_class: "inline" %>
      <% else %>
      <!-- Display login and signup links if the user is not logged in -->
      <%= link_to "Connexion", new_user_session_path, class: "login-link" %>
      <%= link_to "Inscription", new_user_registration_path, class: "signup-link" %>
  <% end %>
</nav>

    <div class="container-web">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with model: [message.subject, message], local: true, html: { class: "custom-form" } do |form| %>
  <% if @message.errors.any? %>
  <div class="error-explanation">
    <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
    <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="form-field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :message_content, class: "form-textarea" %>
  </div>

  <div class="form-actions">
    <%= form.submit class: "form-submit-button" %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id(message) %>" class="message-container">
  <div class="icon-bar">
  <% if message.created_at >= 5.minutes.ago %>
    <%= link_to edit_subject_message_path(@message), class: "edit-message-link", aria_label: "Edit message" do %>
      <i class="fa fa-pencil-alt"></i>
    <% end %>
  <% end %>
  <%= button_to "X", subject_message_path(@message), method: :delete, data: { confirm: "Are you sure?" }, class: "close-button" %>

  </div>
  <p class="message-content">
    <strong>Content:</strong>
    <%= message.content %>
  </p>
  <p class="message-subject">
    <strong>Subject:</strong>
    <%= message.subject_id %>
  </p>
</div>

app/views/messages/_message_preview.html.erb
<!-- app/views/messages/_message_preview.html.erb -->
<div class="quote">
  <strong><%= message.user.name %></strong>
  <br>
  <%= message.content %>
  <br>
  <small><%= message.created_at.strftime("%d %b %Y at %H:%M") %></small>
  <hr> <!-- Séparateur entre les citations -->
</div>

app/views/messages/_message_thread.html.erb
<% messages.each do |message| %>
    <div>
      <strong><%= message.user.name %>:</strong> <%= message.content %>
      <%= render partial: "messages/message_thread", locals: { messages: message.replies } %> if message.replies.any?
    </div>
  <% end %>
  

app/views/messages/_quote_preview.html.erb
<!-- _quote_preview.html.erb -->
<% message.full_quote.each do |quote| %>
    <div class="quote">
      <strong><%= quote.user.name %></strong>
      <br>
      <%= quote.content %>
      <br>
      <small><%= quote.created_at.strftime("%d %b %Y at %H:%M") %></small>
    </div>
    <% unless quote == message.full_quote.last %>
      <hr> <!-- Séparateur entre les citations -->
    <% end %>
<% end %>
  

app/views/messages/edit.html.erb
<%= render "form", message: @message %>

<br>

<div>
<%= link_to subject_path(@subject), class: "back-to-subjects-link", aria_label: "Back to subjects" do %>
  <i class="fas fa-arrow-left"></i> <!-- Icône de flèche gauche -->
<% end %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
    </p>
  <% end %>
</div>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
<%= link_to subject_path(@subject), class: "back-to-subjects-link", aria_label: "Back to subjects" do %>
  <i class="fas fa-arrow-left"></i> <!-- Icône de flèche gauche -->
<% end %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
<%= link_to subject_path(@subject), class: "back-to-subjects-link", aria_label: "Back to subjects" do %>
  <i class="fas fa-arrow-left"></i> <!-- Icône de flèche gauche -->
<% end %>
</div>

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true, html: { class: "custom-form" }) do |form| %>
  <% if subject.errors.any? %>
    <div class="error-explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>
      <ul>
        <% subject.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Hidden field for user_id -->
  <%= form.hidden_field :user_id, value: current_user.id if user_signed_in? %>

  <div class="form-field">
    <%= form.label :title, "Title" %>
    <%= form.text_field :title, class: "form-text-input" %>
  </div>

  <div class="form-field">
    <%= form.label :content, "Content" %>
    <%= form.text_area :content, class: "form-textarea" %>
  </div>

  <div class="form-actions">
    <%= form.submit "Submit", class: "form-submit-button" %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<li class="subject">
  <%= subject.user.name %>
  <br>
  <strong><%= subject.title %></strong>
<br>
  <%= subject.content %>
</li>

app/views/subjects/edit.html.erb
<%= render "form", subject: @subject %>

<br>

<div>
<%= link_to subject_path(@subject), class: "back-to-subjects-link", aria_label: "Back to subjects" do %>
  <i class="fas fa-arrow-left"></i> <!-- Icône de flèche gauche -->
<% end %>
</div>

app/views/subjects/index.html.erb
<%= link_to "New subject", new_subject_path, class: "button-subject" %>

<ul class="list-subjects">
<% @subjects.each do |subject| %>
  <%= link_to subject do %>
      <%= render subject %>
    
  <% end %>
<% end %>
</ul>

app/views/subjects/new.html.erb
<%= render "form", subject: @subject %>

<br>

<div>
<%= link_to subjects_path, class: "back-to-subjects-link", aria_label: "Back to subjects" do %>
  <i class="fas fa-arrow-left"></i> <!-- Icône de flèche gauche -->
<% end %>
</div>

app/views/subjects/show.html.erb
<div class="subject-show-container">
  <%= link_to subjects_path, class: "back-to-subjects-link", "aria-label" => "Back to subjects" do %>
    <i class="fas fa-arrow-left"></i> <!-- Icon of left arrow -->
  <% end %>
  <h1 class="title"><%= @subject.title %></h1>
  <!-- Subject Details -->
  <div class="subject-details">
    <div class="message-header">
      <%= image_tag "user.png", alt: "Profile image", class: "profile-image" %>
      <span class="message-user"><strong><%= @subject.user.name %></strong></span>
      <% if user_signed_in? && current_user == @subject.user %>
        <div class="subject-buttons">
          <% if @subject.created_at >= 5.minutes.ago %>
            <%= link_to edit_subject_path(@subject), class: "edit-subject-link", "aria-label" => "Edit subject" do %>
              <i class="fa fa-pencil-alt"></i>
            <% end %>
          <% end %>
          <%= button_to "X", subject_path(@subject), method: :delete, data: { confirm: "Are you sure?" }, class: "close-button" %>
        </div>
      <% end %>
    </div>
    <div class="message-content">
    <%= youtube_embed(@subject.content) %>
      <%= @subject.content %>
    </div>
  </div>
  <div class="ligne"></div>

  <!-- List of Messages -->
  <ul class="message-list">
  <% if @messages.present? %>
    <% @messages.each do |message| %>
      <li class="message">
        <div class="message-header">
          <%= image_tag "user.png", alt: "User profile image", class: "profile-image" %>
          <span class="message-user"><%= message.user.name %></span>
          <% if user_signed_in? && current_user == message.user %>
            <% if message.created_at >= 5.minutes.ago %>
              <%= link_to edit_subject_message_path(@subject, message), class: "edit-message-link", "aria-label" => "Edit message" do %>
                <i class="fa fa-pencil-alt"></i>
              <% end %>
            <% end %>
            <%= button_to "X", subject_message_path(@subject, message), method: :delete, data: { confirm: "Are you sure?" }, class: "close-button" %>
          <% end %>
        </div>
        <% if message.quoted_message %>
          <div class="quoted-preview" style="position: relative; top: -10px; left: 20px; z-index: 1;">
            <%= render partial: "messages/quote_preview", locals: { message: message } %>
          </div>
        <% end %>
        <div class="message-content">
        <div class="content"><%= youtube_embed(message.content) %></div>
          <br>
          <div class="message-bottom"
            <small class="message-date"><small><%= message.created_at.strftime("%d %b %Y %H:%M") %></small>
            <%= link_to '#', class: "quote-link", data: { 
              subject_id: @subject.id, 
              message_id: message.id, 
              content: message.content, 
              username: message.user.name, 
              date: message.created_at.strftime("%d %b %Y %H:%M") 
            } do %>
              <i class="fa fa-arrow-circle-down" aria-hidden="true"></i> Reply
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  <% else %>
    <p>No messages to display.</p>
  <% end %>
</ul>


  <!-- Form for Creating a New Message -->
  <div class="new-message-form">
  <div id="quote-display" style="display: none;">Citations will appear here</div>
  <%= form_with(model: [@subject, Message.new], local: true) do |form| %>
    <%= form.hidden_field :quote_id, id: "quote_id" %>
      <div class="field">
        <%= form.label :content, "Message:" %>
        <%= form.text_area :content, class: "message-content-textarea" %>
      </div>
      <div class="actions">
        <%= form.submit "Add Message", class: "submit-button" %>
      </div>
    <% end %>
</div>